### ISSUE TITLE
MLFlow Registry of Dolly

### ISSUE THREAD

**Issue by callmesora** [databrickslabs/dolly#112]
How can you log Dolly loaded by HuggingFace transformers into MLFlow?

**Comment by srowen** [comment]
See the blog on mlflow 2.3, with an example: https://www.databricks.com/blog/2023/04/18/introducing-mlflow-23-enhanced-native-llm-support-and-new-features.html

**Comment by callmesora** [comment]
Thanks!

**Comment by srowen** [comment]
How are you running it?

**Comment by srowen** [comment]
I think this is an issue with that demo more than Dolly but it's a reasonable place to discuss it here.

If you're doing this all in one notebook, then I think the problem is that you end up with the model loaded twice - once in the chain you construct, and then when it's reloaded in load_model. It won't fit twice onto the GPU. The second model ends up mostly on the CPU and is very slow as a result.

You can try restarting python before you try to load and query the model this way. I think the demo author is going to add a note or additional code to make that happen instead.

**Comment by callmesora** [comment]
I tried this but still get an error while publishing the model 

"
TypeError: MLflow langchain flavor only supports logging langchain.chains.llm.LLMChain instances, found <class 'langchain.chains.combine_documents.stuff.StuffDocumentsChain'>"


I'm not sure where else to discuss this sorry!

**Comment by srowen** [comment]
You can discuss at github.com/mlflow/mlflow. I think they are going to add support for other chain classes.
