### ISSUE TITLE
I want to use accelerate for multi-new card inference, but I don't know how to set some of the parameters

### ISSUE THREAD

**Issue by hardlipay** [databrickslabs/dolly#137]
model = load_checkpoint_and_dispatch(model, model_path, device_map="auto", no_split_module_classes=["?????"], dtype=torch.float16)

I don't know which modules can't be split, I hope the developers or others will give a list

Thanks！

**Comment by srowen** [comment]
I don't think you necessarily have to set that. Are you seeing an issue? Otherwise you typically set this to the name of the repeated module in the transformer architecture. If you just 'print' the model object itself in the pipeline, it'll show you the architecture and should be obvious, I just don't have it in front of me. It's a normal gpt-neox-based model
