### ISSUE TITLE
How to use domain specific data?

### ISSUE THREAD

**Issue by khayamgondal** [databrickslabs/dolly#185]
Hi,  I have a CSV time series dataset. How can I train that with dolly so I can use dolly prompts?

**Comment by srowen** [comment]
I don't think CSV or time-series data make sense to use with a _language_ model.

**Comment by khayamgondal** [comment]
Thanks, My goal was to be able to retrieve data based on prompts. For ex: "Give me column no. 4 for last 5 days" etc. 
Thats not a use case for the language model?

**Comment by srowen** [comment]
That is more like it - half the problem is natural language, the other half is really code generation. I think this is best framed as "write python code that would read this CSV with pandas and get X" and then execute the code. That's not what Dolly is for, but starcoderbase or replit-code would be a solid place to start for generating code from text
